(*
  Orbison BNF is a dialect containing symbols with the following meanings:
    [ ... ]     Reference a token produced by the lexer

  Below is Orbison BNF grammar defined in itself
*)
<grammar>    ::= <production> <grammar>
               | epsilon;
<production> ::= [IDENTIFIER] "::=" <expression> ";";
<expression> ::= <term>
               | <term> "|" <term>;
<term>       ::= <factor>
               | <factor> <term>;
<factor>     ::= '"' [STRING] '"'
               | "'" [STRING] "'"
               | "<" [IDENTIFIER] ">"
               | "[" [TOKEN] "]"
             ;
