(*
  Orbison BNF is a dialect containing symbols with the following meanings:
    [ ... ]     Reference a token produced by the lexer

  Below is Orbison BNF grammar defined in itself
*)
<grammar>    ::= <production> <grammar>
               | epsilon;
<production> ::= [IDENTIFIER] "::=" <expression> ";";
<expression> ::= <term>
               | <term> "|" <term>;
<term>       ::= <definition>
               | "epsilon";
<definition> ::= <factor>
               | <factor> <definition>
<factor>     ::= '"' [STRING] '"'
               | "'" [STRING] "'"
               | "<" [IDENTIFIER] ">"
               | "[" [TOKEN] "]"
             ;

(*
  DEV NOTES
  ---------
  - any repeated terminals are their own nodes
  -- i.e. IDENTIFER from <production> is a different node than IDENTIFIER from <factor>
  - build top-down and create placeholders for any undefined productions
  - fill in placeholders once there's more info
*)
