(*
  Buffalo is a combined lexer parser
*)
<START> ::= <token_definition> <grammar_definition> <action_definition>;

<token_definition> ::= "tokens" <tokenizer_type> "{" token_block "}";
<token_block> ::= [IDENTIFIER] "=>" [IDENTIFIER] <token_block>
                | "";

<grammar_definition> ::= "grammar" <grammar_type> "{" grammar_block "}";
<grammar_block> ::= "TODO";

<action_definition> ::= "TODO";
